### ISSUE TITLE
[Question] Use in Production Environments

### ISSUE THREAD

**Issue by ncphillips** [MicheleBertoli/react-fix-it#3]
Hey @MicheleBertoli this is a really cool package idea!

I'm wondering if you think this might have a place in a production environment. We're using Sentry and the `redux-raven-middleware`, so being able to send a test to our Sentry server with the error report could be incredibly valuable. 

Let me know if this sounds plausible, and maybe I can help you out with this.

**Comment by MicheleBertoli** [comment]
Hey @ncphillips, thanks for opening the issue.

I've done a lot of [experiments](https://github.com/MicheleBertoli/proper-error-handling) and a couple of [talks](https://speakerdeck.com/michelebertoli/proper-error-handling) about error handling recently.
I ended up using [redux-catch](https://github.com/PlatziDev/redux-catch) to push the state to Sentry on error.

Now, if you are already using a tool that wraps your functions into a `try...catch` block and you are aware of the performance issues related to it, I believe you can use `react-fix-it` in production without any particular problem.

**Comment by brettstack** [comment]
This was my first thought after reading the part in the README about prod. Perhaps allow an overridable function here https://github.com/MicheleBertoli/react-fix-it/blob/master/src/fix-it.js#L16 , with the default being `test => console.log(test)`.

**Comment by MicheleBertoli** [comment]
That's a very good idea, thanks @brettstack.
I pushed `v0.3.0` that makes possible to set a custom logging function.
