### ISSUE TITLE
Help understanding what the workflow looks like to use this.

### ISSUE THREAD

**Issue by awhit012** [MicheleBertoli/react-fix-it#4]
Hi Michele! 

I just watched your "How to test like it's 2017" and really enjoyed it. react-fix-it looks really exciting! I'm having a little trouble understanding what the workflow of debugging looks like by looking at the readme. Could you possibly do a demo that shows set up and the process, or explain it a little more in-depth in the readme? Right now the demo works on my machine, but I'm not getting any tests in the console or screen on my app on my local. Do I need to be calling fixit(myModule) on every module? 

Thanks so much, 

Alex

**Comment by MicheleBertoli** [comment]
Thank you very much for your comment, @awhit012.
I'm glad you liked the talk and the library.

> Could you possibly do a demo that shows set up and the process, or explain it a little more in-depth in the readme?

I'm sorry the README is not clear, but the "set up" only consists in wrapping a component with `fixIt`.

> Do I need to be calling fixit(myModule) on every module?

Yes, all the modules must be wrapped and the easiest way is to use [babel-plugin-react-fix-it](https://github.com/MicheleBertoli/babel-plugin-react-fix-it).

I hope this helps.
